### ISSUE TITLE
Time of Day levelling system

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#123]
Suggested by Oath

This will level mobs differently depending on the time of day of the world they spawn in.

**Comment by lokka30** [comment]
See #242

**Comment by UltimaOath** [comment]
Using the 3.1.X feature PlayerStat Levelling, once Penal creates a PAPI tag to reflect the current time of day in ticks called '%world_time_ticks%', we will be able to achieve this levelling system. I will update further once development and testing has finalized.

**Comment by lokka30** [comment]
> 
> 
> Using the 3.1.X feature PlayerStat Levelling, once Penal creates a PAPI tag to reflect the current time of day in ticks called '%world_time_ticks%', we will be able to achieve this levelling system. I will update further once development and testing has finalized.

Oh, woot! So we don't even need to add in our own code to accomplish it.

**Comment by stumper66** [comment]
added to 3.2.0 b514
syntax:
```
    conditions:
      world-time-tick:
        allowed-list: ['0-600', '18000-24000']
        excluded-list: ['22000-23000']
```
