### ISSUE TITLE
Chance to have specific equipment

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#13]
Feature request by SpigotMC user [soloman981](https://www.spigotmc.org/members/soloman981.120314/)

The user says:
'Feature idea > Chance percentage to have specific equipment. The higher the level the higher the chance for a mob to have a set item.'

Since I still don't know how to scan for sections with LightningStorage, I will have to make an 'enabled-chances' section where each chance used would have to be specified there.
OR, i could loop through 1-100 each time.

It will also be annoying to cache this, it will need a custom EquipmentChance object.

This is my interpretation of the idea, posed in settings.yml:

```
equipment-chances:
 30:
  main_hand: WOODEN_SWORD
  off_hand: AIR
  helmet: AIR
  chestplate: LEATHER_TUNIC
  leggings: IRON_LEGGINGS
  boots: IRON_BOOTS
 10:
  main_hand: STONE_SWORD
  off_hand: APPLE
  helmet: LEATHER_CAP
  chestplate: GOLDEN_CHESTPLATE
  leggings: CHAINMAIL_LEGGINGS
  boots: CHAINMAIL_BOOTS
```

so, it's formatted this way:
```
 chance:
  inventory-location: material
```

offhand isn't used by mobs so it doesn't have to be added, but more features don't hurt
