### ISSUE TITLE
Add level cap for mob reinforcements

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#130]
Suggested  by squeebis#4466

is there away to set a level cap for zombie reinforcements? im getting absolutely roasted in hardmode by these guys hahahaha

**Comment by lokka30** [comment]
This is a great suggestion that would not be difficult to implement. Example:

```
limit-zombie-reinforcements:
  enabled: true
  min-level: 1
  max-level: 1
```
