### ISSUE TITLE
Allow users to customise mob names

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#17]
SpigotMC user  Niemiluch said on my profile:

> hi, you have created a really extra plugin - LevelledMobs , but I have a question, do you ever plan to add the option of e.g. changing the name of the mobs? this could be useful for servers that are not in English :)

Unfortunately it is currently out of my skill level as I am still getting used to the LightningStorage methods.

I would imagine it like this:
```
settings.yml:
 mob-name-translate:
  ZOMBIE: 'Brain Eater'
 CREEPER: 'Corrupted Pig'
```
