### ISSUE TITLE
Request: When '/nodrops' is used in 'kill', include info in the msg.

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#207]
> My only other suggestion related to the /nodrops is to include a messages.yml update to include text when applying no drops.

```
all:
  nodrops:
    - '%prefix% Killed &b%killed%&7 levelled mobs in &b%worlds%&7 world(s) &8(&b%skipped%&7 mobs were skipped; &bNo-Drops applied&8)&7.'
  near:
    nodrops:
      - '%prefix% Killed &b%killed%&7 levelled mobs within a radius of &b%radius%&7 block(s) &8(&b%skipped%&7 mobs were skipped; &bNo-Drops applied&8)&7.'
```

suggested by Oath
