### ISSUE TITLE
Request: Entity-name-override should accept lists of names

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#213]
UltimaOath suggests:

> Be able to create a list of randomly chosen names for an entity. For example:

```
entity-name-override:
  WITHER: 'Wither'
  CREEPER: ['Boomer', 'Splosive', 'Nitro']
```

**Comment by stumper66** [comment]
Added to 3.0 b387.
Tested with this config:
```
  entity-name-override:
    CREEPER: 'Mr Self Destruct'
    ZOMBIE: ['Undead','Brainless','Mr Joe','Flesh Biter']
    BABY_ZOMBIE: 'Baby Undead'
```
