### ISSUE TITLE
Request: Variable slime size

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#235]
**Is your feature request related to a problem? Please describe.**
Slimes stay at the same size regardless of their level. Perhaps we can utilise their size in the plugin.

**Describe the solution you'd like**
Auxilor in our Discord suggested that slimes could optionally become larger as they level-up.

**Describe alternatives you've considered**
N/A

**Additional context**
[Link to conversation](https://discord.com/channels/752310043214479462/760051505067458590/858502640538091560)

**Comment by UltimaOath** [comment]
With Penal's addition of NBT-API stuff into CustomDrops, I don't see why we couldn't utilize the same system to be able to include nbt data into entities using custom rules (which would do what is desired here, as well as open the door to unlimited nbt flex on entities). Here's my minds' eye:

```
  - enabled: true
    name: 'CR - King Slime'
    conditions:
      worlds:
        allowed-list: ['world']
      entities:
        allowed-list: ['SLIME']
    apply-settings:
      minLevel: 10
      nbt: '{Size:100}'
```

With the `nbt:` config line, it will simply append the nbt data to the entity as it does with CustomDrops as of 3.0.4 :)
