### ISSUE TITLE
Request: Loot tables & custom drops can optionally require a permission when a player kills a levelled mob

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#237]
See conversation [here](https://discord.com/channels/752310043214479462/829238692161781770/860517485777125426).

Suggested by `ojmaster#7182`

**Comment by lokka30** [comment]
Any idea for which version we should implement this? 3.1, 3.2, 3.3, 3.4? @stumper66

**Comment by UltimaOath** [comment]
\-dumping my comment from Discord here for ease in the future-  
Here's how I'd implement:  
\`\`\`yml - enabled: true  
   name: 'Requires Permission'  
   conditions:  
     permission:  
       allowed-list: \['node'\]  
   apply-settings:  
     use-droptable-id: X  
\`\`\`

Would only apply to use-droptable-id:  
The node represented as lm.permission.node

As for implementation in CustomDrops:  
\`\`\`yml  
\- ZOMBIE:  
 - DIAMOND:  
     overall-permission: \['node1', 'node2'\]  
     permission: \['node1', 'node2'\]  
\`\`\`  
Where overall-permission: reflects on all drops of the entitytype (similar to how overall-chance works), while permission: reflects per item. (unless we can do the same modallist structure for the CD).

**Comment by stumper66** [comment]
Added to v3.2.0 b524

**Comment by stumper66** [comment]
Rule example:
```
  - enabled: false
    name: 'test'
    conditions:
      permission:
        allowed-list: ['testperm']
    apply-settings:
      nametag: 'I &#F2003D%heart_symbol%&r PenalBuffalo!'
      use-droptable-id: 'drop1'
```

custom drop example:
```
HUSK:
  - overall_permission: ['node1', 'testperm']
  - IRON_CHESTPLATE:
#      overall_chance: 1.0 # Chance for any object to process for the Zombie.
      drop-chance: 0.8 # Chance for this individual object to process.
      equipped: 0.5
      chance: 0.91
  - IRON_LEGGINGS:
      drop-chance: 0.8 # Chance for this individual object to process.
      equipped: 0.5
      chance: 0.92
      #overall_permission: ['node1', 'testperm']
      permission: ['node1', 'testperm']
```
