### ISSUE TITLE
Request: Request: New Rule Condition: Player Level Min/Max

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#248]
**Is your feature request related to a problem? Please describe.**
Add a new rule condition that takes into consideration the level of the player that killed the mob.  Can use a min or max condition.
This would allow high level players to receive or deny things that don't apply to lower level players

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by stumper66** [comment]
Added to 3.2.0 b516
Instead of hard-coding player level it supports the same variable system that player levelling uses.
Here is an example config:
```
ZOMBIE:
  - iron_sword:
      chance: 1.0
      min-player-level: 10
      max-player-level: 12
      player-level-variable: '%level%'
```
