### ISSUE TITLE
Permission Dependent Drop Probability

### ISSUE THREAD

**Issue by jeffry1829** [lokka30/LevelledMobs#284]
Seems like there's no easy way to increase the drop chance(or customCommand chance) in player basis

Thus, I hope there's a setting in customdrops.yml that can specify the chance for individual players.
For example, the player with permission `leveledmobs.individual_chance_enhance` can have higher chance of dropping item or executing commands.

Sample customdrops.yml:
```
- customCommand:
    command: 'money give %player% %ranged_h%'
    minLevel: 71
    maxLevel: 75
    chance: 0.5
    ranged_h: 2001-3500
    chance_enhance: [leveledmobs.individual_chance_enhance.lvl71to75, 0.3]
    chance_override: [leveledmobs.individual_chance_override.lvl71to75, 1.0]
```
Then the chance will be 0.5+0.3 or 1.0 depending on the permission node.

Also, it's good if we can have shortcut like this:
```
chance_enhance: 'leveledmobs.individual_chance_enhance._X_'
chance_override: 'leveledmobs.individual_chance_enhance._X_'
```
Then, by default, the player with permission `leveledmobs.individual_chance_enhance._0.3_` will have drop chance *default chance*+0.3

Thanks! :p
