### ISSUE TITLE
Add 'No Downgrade' player levelling

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#295]
We should add an apply-setting to the Player Levelling system that prevents mobs from decreasing their level when different players with different levels engage with the boss mob.

If a higher level player comes near then it will still level. The mob just doesn't decrease their level.

I'm thinking this should go in LM 4.1 but of course can be added earlier

**Comment by UltimaOath** [comment]
I think this could be implemented as such:

```yaml
    strategies:
      player-levelling:
        match-level: true
        use-player-max-level: false
        player-level-scale: 1.0
        level-cap: 30
        tiers:
          1-15: 1-10
          16-30: 11-20
          31-45: 21-25
        variable: '%level%'
        
        decrease-level: true
```

With default `true`, when `false` , once an entity has been relevelled once, it will not relevel again unless the new level is higher than it's current level.
