### ISSUE TITLE
Cause of Death feature improvements in CustomDrops

### ISSUE THREAD

**Issue by UltimaOath** [lokka30/LevelledMobs#300]
```yml
- ZOMBIE:
  - DIAMOND:
      player-caused: true
      cause-of-death: ['FIRE', 'FIRE_TICK', 'LAVA']
```
https://discord.com/channels/752310043214479462/757933745620779033/893959075619045437

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html

Using the above list, and the modallist system, allow for the cause of death to be checked prior to dropping items. Leave `player-caused:` alone, as it's a central item. Will need to experiment with the feature to see what specific things are the easiest to activate and most likely to be used.

**Comment by stumper66** [comment]
Added to LM 3.3.0 b560

cause-of-death was implemented as the standard modal list which means all the following combinations are available:
```
HUSK:
  - IRON_SWORD:
      chance: 1.0
      equipped: 0
      player-caused: false
      cause-of-death: ['FIRE', 'FIRE_TICK', 'LAVA']

# OR:
  - IRON_SWORD:
      chance: 1.0
      equipped: 0
      player-caused: false
      cause-of-death: 'FIRE'

# OR:
  - IRON_SWORD:
      chance: 1.0
      equipped: 0
      player-caused: false
      cause-of-death:
        excluded-list: ['ENTITY_ATTACK', 'HOT_FLOOR', 'FALL']

# OR:
  - IRON_SWORD:
      chance: 1.0
      equipped: 0
      player-caused: false
      cause-of-death:
        allowed-list: ['SUFFOCATION', 'POISION', 'MAGIC']
```

**Comment by stumper66** [comment]
Example debug messages:
```
[13:24:05 INFO]: LevelledMobs: drop instances: 1, custom groups: 0, item groups: 0, items: 1, commands: 0
mob: HUSK
    IRON_SWORD, amount: 1, chance: 1.0, lst: [FIRE, FIRE_TICK, LAVA]

Entity didn't meet death cause criteria:
[13:24:25 INFO]: LevelledMobs: Custom drops for HUSK (level 2)
- Groups: ALL_GROUND_MOBS, ALL_HOSTILE_MOBS, ALL_LEVELLABLE_MOBS, ALL_MOBS, ALL_OVERWORLD_MOBS.
 - item: IRON_SWORD, death-cause: ENTITY_ATTACK, death-cause-req: lst: [FIRE, FIRE_TICK, LAVA], dropped: false.
 --- Custom items added: 0.

Met death cause criteria:
[13:28:44 INFO]: LevelledMobs: Custom drops for HUSK (level 2)
- Groups: ALL_GROUND_MOBS, ALL_HOSTILE_MOBS, ALL_LEVELLABLE_MOBS, ALL_MOBS, ALL_OVERWORLD_MOBS.
 - item: IRON_SWORD, amount: 1, newAmount: 1, chance: 1.0, chanceRole: 0.0, dropped: true.
 --- Custom items added: 1.

```

**Comment by UltimaOath** [comment]
Tested in 3.3.0 b560 - Working as expected!  
  
Note: Next build; ignore `player-caused:` setting for items with `cause-of-death:` , as they're conflicting features. Currently we require most users who want to use `cause-of-death:` to also include `player-caused: false` in order for the drop to function. This way the setting will not require the extra config option.

**Comment by stumper66** [comment]
> Tested in 3.3.0 b560 - Working as expected!
> 
> Note: Next build; ignore `player-caused:` setting for items with `cause-of-death:` , as they're conflicting features. Currently we require most users who want to use `cause-of-death:` to also include `player-caused: false` in order for the drop to function. This way the setting will not require the extra config option.

This was updated in 3.3.0 b561.

Even using the config below, it will drop the item without any player interaction.
```
HUSK:
  - IRON_SWORD:
      chance: 1.0
      equipped: 0
      player-caused: true
      cause-of-death: ['FIRE', 'FIRE_TICK', 'LAVA']
```
