### ISSUE TITLE
Entity Buffs / Nerfs System using DamageCause Event

### ISSUE THREAD

**Issue by UltimaOath** [lokka30/LevelledMobs#302]
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html

Using this list or similar, craft a `apply-settings:` that allows for buffs and debuffs based on kind of damage applied to entity.

```yaml
apply-settings:
  buffs: # Range only 0.0 - 1.0
    BLOCK_EXPLOSION: 1.0 # 100% decrease in damage from this event
    ENTITY_ATTACK: 0.2 # 20% decrease in damage from this event
  nerfs: # Range 0.0+
    LIGHTNING: 1.0 # 100% increase in damage from this event
    POISON: 0.2 # 20% increase in damage from this event
    SUFFOCATION: 2.0 # 200% increase in damage from this event
```
