### ISSUE TITLE
Allow player levelling tiers with strings

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#315]
Suggested by 이팩터#5621

They have a plugin that returns different PAPI variable string, such as `easy`, `normal`, etc.
This would map to a player levelling tier instead of the normal source level range.
Config example:
```
      player-levelling:
        match-level: false
        use-player-max-level: false
        player-level-scale: 1.0
        level-cap: 30
        tiers:
          'easy': 1-10
          'normal': 11-20
          'something else': 21-25
        variable: '%rtupd_name%'
```

**Comment by stumper66** [comment]
Added to 3.3.0 b570.

Config example:
```
      player-levelling:
        match-level: false
        use-player-max-level: false
        player-level-scale: 1.0
        level-cap: 30
        tiers:
          NETHERITE_HELMET: 1-3
          NETHERITE_CHESTPLATE: 3-6
          netherite_leggings: 7-9
          1-15: 1-10
          16-30: 11-20
          31-45: 21-25
        #variable: '%armor_material_helmet%'
        #variable: '%armor_material_chestplate%'
        variable: '%armor_material_leggings%'
```

debug message with a matching tier:
```
[13:50:54 INFO]: LevelledMobs: [Debug: PLAYER_LEVELLING] mob: ZOMBIE, player: PenalBuffalo, lvl-src: 'NETHERITE_LEGGINGS', tier: netherite_leggings: [7, 9], cap: 30, result: [7, 9]
```

debug message with no matching tiers:
```
[13:51:15 INFO]: LevelledMobs: [Debug: PLAYER_LEVELLING] mob: ZOMBIE, player: PenalBuffalo, lvl-src: 'NETHERITE_BOOTS', cap: 30, no tiers matched
```
