### ISSUE TITLE
Player Levelling Change ; Scale Multipliers

### ISSUE THREAD

**Issue by UltimaOath** [lokka30/LevelledMobs#319]
> ParseBadData — Today at 1:47 PM
> Well I want for the levels and multipliers to change, like having them be calculated separately. Like a formulla that I have right now that is basically (archery+fighting+defense)/0.33 = monster's level, but for their HP multiplier to change with (archery+fighting)/0.5, so its like if the formulla gives 2, it would change the HP scaling to 2.0, but if it's something like 97 the HP scaling would be 15.0

https://discord.com/channels/752310043214479462/760051505067458590/905906023611646032

TLDR: The ability for Player Levelling to make changes to the multipliers independently to the levels.

I'll have to return to this topic with potential config arrangements for such a system, as well as how it might be implemented.

**Comment by UltimaOath** [comment]
```yaml
strategies:
  player-levelling:
    match-level: false
    use-player-max-level: false
    player-level-scale: 1.0
    level-cap: 30
    tiers:
      1-15: 1-10
      16-30: 11-20
      31-45: 21-25
      v1-v2: lvl-lvl
    variable: '%level%'
    
    
    
    multiplier-scaling:
      variable: '%all_multipliers%'
      max-health:
        tiers:
          1: 1-100
          2: 101-200
          4: 201-300
          8: var-var
        variable: '%health_multiplier%'
      movement-speed:
        tiers:
          0.025: 1-100
          etc....
```
