### ISSUE TITLE
Allow multiple NBT definitions and merge support

### ISSUE THREAD

**Issue by stumper66** [lokka30/LevelledMobs#323]
When defining nbt-data in a rule, allow multiple definitions.
Also add support for merging nbt-data from different rules.

**Comment by stumper66** [comment]
added to LevelledMobs v3.3.0 b563

Basic syntax remains the same:
```
nbt-data: '{Silent:1,NoAI:1}'
```
it supports array-lists:
```
nbt-data:
- '{Silent:1}
- {NoAI:1}'
```

and can merge rules, but uses a slightly different syntax:
```
# rule 1
nbt-data:
  data: '{Silent:1}'
  merge: true

# rule 2
nbt-data: '{NoAI:1}''
```
