### ISSUE TITLE
Hardcore Featureset

### ISSUE THREAD

**Issue by UltimaOath** [lokka30/LevelledMobs#324]
```yaml
  apply-settings:

    hardcore:
      deathboost: true

      secondchance:
        count: 1
        health_remaining: 10
        health_restored: 20

      rollattributes:
        challenge-rating: 1.0
        max-health: true
        movement-speed: true
        attack-damage: true

      mobraid: true

      endermanwarp: true
```

This system could be expanded upon with more features in the future. The reason I suggest separating them is because I believe these settings give entities an extra advantage beyond what we normally would apply otherwise.

The first suggestion regarding `deathboost:` ; when this is enabled, if an entity kills a player, that entity will be levelled up by one level and fully healed up (can be 'relevelled', under current arrangements, the health and attributes would correct themselves). This can be represented as a `true` or `false`, or can be numerical chance `0.0` through `1.0` to apply.

---

The second suggestion regarding `secondchance:` ; when this is enabled, LM would detect when an entity is at `health_remaining:` percent health, and then restore `health_restored:` percent of health to the entity, a maximum of `count:` times.

[https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/EntityResurrectEvent.html](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/EntityResurrectEvent.html)

---

The third suggestion regarding `rollattributes:` ; when this is enabled, LM would select a value between the default and the configured result, and replace the attribute with this new value; then levelling can occur. This applies a randomness to all listed attributes to provide a challenge rating.   
For example, if an entity would spawn with 40hp, and the `challenge-rating: 1` , then `(40 + (40 x 1)) = 80` ; LM then selects a value between `40-80` and replaces the default before levelling.

---

The fourth suggestion regarding `mobraid:` ; when an entity is attacked by a player, any other entity within 16 blocks will also know where the player is located and head for that direction.

---

The fifth suggestion regarding `endermanwarp:` ; when an entity is hit by a player, it is teleported in the same fashion that an Enderman would teleport to protect itself. Got the idea from this conversation (includes some beginning code steps):

[https://www.spigotmc.org/threads/entity-teleport-like-enderman-help.510001/](https://www.spigotmc.org/threads/entity-teleport-like-enderman-help.510001/)
