### ISSUE TITLE
Add 'Phase of the Moon' condition

### ISSUE THREAD

**Issue by UltimaOath** [lokka30/LevelledMobs#332]
```yaml
  conditions:
    moon-phase:
      allowed-list: ['NEW_MOON', 'WANING_GIBBOUS, 'THIRD_QUARTER', 'WANING_CRESCENT', 'NEW_MOON', 'WAXING_CRESCENT', 'FIRST_QUARTER', 'WAXING_GIBBOUS']
```

Excel Spreadsheet with concept proven with math:
[The Receipts](https://discord.com/channels/752310043214479462/757933745620779033/912113722749771806)

This would be a condition check against the current phase of the moon. This will need to include a limit where the time of day needs to be between `13000` and `23000` as that's the only time the moon would be out. The math of determining the current phase is fairly simply.
