### ISSUE TITLE
Infernal Mobs compat possibly broken

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#342]
See [this post](https://www.spigotmc.org/threads/levelledmobs-for-1-16-x-1-18-x.412953/page-20#post-4323513).

**Comment by UltimaOath** [comment]
I have taken the time to verify that LevelledMobs and InfernalMobs has good compat within the latest 1.17 and 1.18.1 Paper builds. There are additional steps that users within InfernalMobs must take in order to hide the nametags from InfernalMobs, or to somewhat reduce the levelling of their entities.

Here is the complete config.yml file I'm using with a functional InfernalMobs (they're still levelled, but nametags are hidden):
```yaml
# Chance is the chance that a mob will not be infernal, the lower the number the higher the chance. (min 1)
# Enabledworlds are the worlds that infernal mobs can spawn in.
# Enabledmobs are the mobs that can become infernal.
# Loot is the items that are dropped when an infernal mob dies. (You can have up to 64)
# Item is the item, Amount is the amount, Durability is how damaged it will be (0 is undamaged).
# nameTagsLevel is the visibility level of the name tags, 0 = no tag, 
# 1 = tag shown when your looking at the mob, 2 = tag always shown.
# Note, if you have name tags set to 0, on server restart all infernal mobs will turn normal.
# If you want to enable the boss bar you must have BarAPI on your server.
# nameTagsName and bossBarsName have these special tags: <mobLevel> = the amount of powers the boss has.
# <abilities> = A list of about 3-5 (whatever can fit) names of abilities the boss has.
# <mobName> = Name of the mob, so if the mob is a creeper the mobName will be "Creeper".
chance: 100
namePrefix: '&fInfernal'
nameTagsLevel: 0     # removes InfernalMob nametag to use LM alone.
nameTagsName: '&f<prefix> <mobName>'
bossBarsName: '&fLevel <mobLevel> &f<prefix> <mobName>'
enableBossBar: false     # disable InfernalMob bossbar for same reason above.
bossBarSettings:
  defaultColor: PINK
  defaultStyle: SOLID
enableScoreBoard: false
showHealthOnScoreBoard: true
effectAllPlayerAttacks: true
enableParticles: true
enableDeathMessages: false
deathMessages:
- '&cplayer &chas killed an mob&c!'
- '&cAn mob &cwas slain by player&c!'
- '&cplayer &cowned an mob&c!'
- '&cAn mob &cwas beheaded by player&c''s weapon!'
- '&cplayer&c''s weapon &ckilled an mob&c!'
- '&cAn mob &cwas killed by player &cusing a weapon&c!'
enableSpawnMessages: false
spawnMessageRadius: 64
spawnMessages:
- '&cAn Infernal mob has spawned near you!'
- '&cWatch out!'
- '&cYou hear a faint scream...'
- '&cSomething is coming...'
- '&cYou hear a mob nearby...'
mobworlds:
- <all>
effectworlds:
- <all>
enabledmobs:
- ELDER_GUARDIAN
- WITHER_SKELETON
- STRAY
- HUSK
- ZOMBIE_VILLAGER
- SKELETON_HORSE
- ZOMBIE_HORSE
- EVOKER
- VEX
- VINDICATOR
- CREEPER
- SKELETON
- SPIDER
- GIANT
- ZOMBIE
- SLIME
- GHAST
- PIG_ZOMBIE
- ENDERMAN
- CAVE_SPIDER
- SILVERFISH
- BLAZE
- MAGMA_CUBE
- ENDER_DRAGON
- WITHER
- BAT
- WITCH
- ENDERMITE
- GUARDIAN
- SHULKER
- ILLUSIONER
- PARROT
- POLAR_BEAR
- LLAMA
- DROWNED
- PHANTOM
- PUFFERFISH
- BEE
- PIGLIN
- HOGLIN
- ZOGLIN
- STRIDER
- ZOMBIFIED_PIGLIN
enabledCharmSlots:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 40
- 36
- 37
- 38
- 39
poisonous: true
armoured: true
blinding: true
withering: true
tosser: true
thief: true
quicksand: true
bullwark: true
rust: true
sapper: true
1up: true
cloaked: true
ender: true
ghastly: true
lifesteal: true
sprint: true
storm: true
webber: true
vengeance: true
weakness: true
berserk: true
explode: true
potions: true
mama: true
molten: true
archer: true
necromancer: true
firework: true
gravity: true
flying: true
mounted: true
morph: true
ghost: true
confusing: true
mamaSpawnAmount: 3
vengeanceDamage: 6
berserkDamage: 3
moltenBurnLength: 5
gravityLevitateLength: 6
horseMountsHaveSaddles: true
armouredMountsHaveArmour: true
fireworkColour:
  red: 255
  green: 10
  blue: 10
enabledSpawnReasons:
- BREEDING
- BUILD_WITHER
- CHUNK_GEN
- CUSTOM
- DEFAULT
- INFECTION
- SPAWNER_EGG
- LIGHTNING
- NATURAL
- NETHER_PORTAL
- OCELOT_BABY
- REINFORCEMENTS
- SILVERFISH_BLOCK
- SLIME_SPLIT
- VILLAGE_INVASION
mobParticles:
- lavaSpark:1:10
mountFate: nothing
enabledMounts:
- SPIDER
- SKELETON_HORSE
- ZOMBIE_HORSE
- DONKEY
- MULE
- SLIME
- GHAST
- MAGMA_CUBE
- ENDER_DRAGON
- BAT
- PIG
- SHEEP
- COW
- CHICKEN
- MUSHROOM_COW
- HORSE
- POLAR_BEAR
- LLAMA
- PHANTOM
- HOGLIN
- ZOGLIN
- STRIDER
enabledRiders:
- WITHER_SKELETON
- STRAY
- HUSK
- ZOMBIE_VILLAGER
- EVOKER
- VINDICATOR
- SKELETON
- ZOMBIE
- PIG_ZOMBIE
- ENDERMAN
- WITCH
- SNOWMAN
- VILLAGER
- ILLUSIONER
- DROWNED
- ZOMBIFIED_PIGLIN
- PIGLIN
disabledBabyMobs:
- WOLF
- MUSHROOM_COW
- COW
- SHEEP
- PIG
- CHICKEN
- OCELOT
- HORSE
minpowers: 3
maxpowers: 7
healthMultiplier: 4
healthByPower: false
healthByDistance: false
powerByDistance: false
healthToAdd: 5
powerToAdd: 1
xpMultiplier: 8
addDistance: 200
enableDrops: true
dropChance: 1
enableFarmingDrops: false
naturalSpawnHeight: 0
configVersion: 'git-Paper-73 (MC: 1.18.1)'
```

From within the current latest `config.yml` file from InfernalMobs:
| Config Line | What you're changing |
| ---------- | ---------- |
| `nameTagsLevel:` | Change this value to `2`. Doing this will clear any secondary nametags and give the entity their 'Infernal' name. Setting to `1` will cause dual nametags to appear from time to time; Setting this to `0` disables InfernalMobs nametag system entirely, which is not ideal. |
| `enableBossBar:` | Change this value to `false`. Doing this will clear the bossbar effect at the top of the screen when encountering an InfernalMob, thus removing any display of Level. You can also choose to alter the `bossBarsName:` and remove the InfernalMob level display tag. |
| `healthMultiplier:`, `healthToAdd:`, `xpMultiplier:` | Change these values to `0`. Doing this will prevent InfernalMobs from adjusting the health of the entities, and instead allowing LevelledMobs to adjust this value as if from the base value of the entity. This can be adjusted as desired, though zero is the suggested value. |

The end result :)

![image](https://user-images.githubusercontent.com/19399136/146619159-217d573c-3630-4fdc-90ba-c366c88084f3.png)
