### ISSUE TITLE
Priority for the Default Rule

### ISSUE THREAD

**Issue by Cokenpizza** [lokka30/LevelledMobs#356]
The ability to set "priority" for the default rule.  ie: have spawn AND player levelling enabled, but choose to use player levelling only if spawn levelling would be higher or lower.

UltimaOath gave a great custom rule option as found in the discord https://discord.com/channels/752310043214479462/760051505067458590/934131075234557953 but a less lengthy system would be more convenient

  - enabled: true
    name: 'Player Levelling / Distance from Spawn / Part 1'
    conditions:
      min-distance-from-spawn: 1000
      max-distance-from-spawn: 2500
    strategies:
      player-levelling:
        match-level: false
        use-player-max-level: false
        decrease-level: true
        player-level-scale: 1.0
        level-cap: 30
        tiers:
          1-15: 1-10
          16-30: 11-20
          31-45: 21-25
        variable: '%level%'

  - enabled: true
    name: 'Player Levelling / Distance from Spawn / Part 2'
    conditions:
      min-distance-from-spawn: 2501
      max-distance-from-spawn: 3500
    strategies:
      player-levelling:
        match-level: false
        use-player-max-level: false
        decrease-level: true
        player-level-scale: 1.0
        level-cap: 30
        tiers:
          1-15: 5-10
          16-30: 15-20
          31-45: 25-25
        variable: '%level%'

**Comment by UltimaOath** [comment]
While there exists the `decrease-level: true` for Player Levelling, which will not update the level unless the level that would be created from Player Levelling is higher than the entities' current level if it's set to `false`. As for the reverse, that doesn't yet exist however I will investigate a method for LM4 to take advantage of this condition check :)

**Comment by UltimaOath** [comment]
```yaml
    strategies:
      player-levelling:
        match-level: true
        use-player-max-level: false

#       Instead of:
        decrease-level: true
        
#       Change to:
        keep-within-variance: 0
        increase-level: true
        decrease-level: true

        player-level-scale: 1.0
        level-cap: 30
        tiers:
          1-15: 1-10
          16-30: 11-20
          31-45: 21-25
        variable: '%level%'
```

`keep-within-variance:` - This value means that the level cannot be altered if the new value would be more than X levels from the entities' current level, where X is the `keep-within-variance:` value. If the value is `0`, then this config will be ignored. The default should be `0`.   
`increase-level:` - This value, when `false`, means that the level cannot be altered if the new value would be higher than the entities' current level. When `true`, the level will be allowed to go above the entities' current level, as long as it's within any previous settings like variance. The default should be `true`.   
`decrease-level:` - This value, when false, means that the level cannot be altered if the new value would be lower than the entities' current level. When `true`, the level will be allowed to go below the entities' current level, as long as it's within any previous settings like variance. The default should be `true`. (I'm fairly sure this is how it's done currently, but for syncing my ideas purposes I wanted to put it all on the table).
