### ISSUE TITLE
How to set the LM according to the difficulty level of each world on multiple world servers.

### ISSUE THREAD

**Issue by itcools** [lokka30/LevelledMobs#368]
Hi..

I set the difficulty level of my server, which has 10 worlds, to be easy, ordinary, and difficult.

I want to set the LM according to the difficulty level of each world, but I don't know what to do. Can someone help me?

**Comment by stumper66** [comment]
@itcools you'll want to create a fewcustom rules. Leave the default rule as normal and change your allowed world preset to only have those worlds using it.
Then create custom rules for easy and hard:

```
  - enabled: true
    name: 'Easy worlds'
    use-preset: easy_difficulty
    conditions:
      worlds: ['world1', 'world2']

  - enabled: true
    name: 'Hard worlds'
    use-preset: hard_difficulty
    conditions:
      worlds: ['world3', 'world4']
```

Make sure the above rules go in your custom-rules section.
I recommend joining discord so we can interact with you in real-time.
