### ISSUE TITLE
Ranged attack damage multiplier does not seem to have any effect

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#389]
Bug confirmed by reporter

Reported by AlternativeSoap

[Discord message link](https://discord.com/channels/752310043214479462/760051505067458590/984457190385532989)

<details>
<summary>Rules file submitted by reporter</summary>

> Some comments have been removed for easy access

```yaml
mob-groups:
  commons:
    - ZOMBIE
    - SKELETON
    - CREEPER
  farm:
    - CHICKEN
    - COW
    - SHEEP
    - PIG


biome-groups:
  taigas:
    - TAIGA
    - TAIGA_MOUNTAINS
    - SNOWY_TUNDRA
    - SNOWY_TAIGA
    - SNOWY_TAIGA_HILLS
    - GIANT_TREE_TAIGA
    - GIANT_SPRUCE_TAIGA
    - GIANT_SPRUCE_TAIGA_HILLS
    - GIANT_TREE_TAIGA_HILLS
    - SNOWY_TAIGA_MOUNTAINS
  flowers:
    - FLOWER_FOREST
    - SUNFLOWER_PLAINS

presets:
  spawn_Levelling:
    name: 'LVLling Strategy - Distance-From-Spawn'
    strategies:
      distance-from-spawn:
        increase-level-distance: 150
        start-distance: 250
        spawn-location:
          x: default
          z: default

  blended_Levelling:
    name: 'LVLling Strategy - Blended-Levelling'
    strategies:
      distance-from-spawn:
        blended-levelling:
          enabled: true
          transition-y-height: 62
          lvl-multiplier: 0.05
          multiplier-period: 10
          scale-downward: true

  random_Levelling:
#   This Strategy Preset controls the Random-Levelling system.
    name: 'LVLling Strategy - Random'
    strategies:
      random: true
      lower-mob-level-bias-factor: 5

  weighted_random_hard:
#   This Strategy Preset controls Weighted Random Bias.
    name: 'LVLling Strategy - Weighted Random Bias HARD DIFFICULTY'
    strategies:
      weighted-random:
        1-10: 5
        11-20: 4
        21-30: 3
        31-40: 2
        41-50: 1

  weighted_random_normal:
#   This Strategy Preset controls Weighted Random Bias.
    name: 'LVLling Strategy - Weighted Random Bias NORMAL DIFFICULTY'
    strategies:
      weighted-random:
        1-5: 5
        6-10: 4
        11-15: 3
        16-20: 2
        21-25: 1

  weighted_random_easy:
#   This Strategy Preset controls Weighted Random Bias.
    name: 'LVLling Strategy - Weighted Random Bias EASY DIFFICULTY'
    strategies:
      weighted-random:
        1-2: 5
        3-4: 4
        5-6: 3
        7-8: 2
        9-10: 1

  player_Levelling:
#   This Strategy Preset controls the player-stat based levelling system.
    name: 'LVLling Strategy - Player Based NORMAL DIFFIULTY'
    strategies:
      player-levelling:
        match-level: true
        use-player-max-level: false
        player-level-scale: 1.0
        level-cap: 30
        tiers:
          1-15: 1-10
          16-30: 11-20
          31-45: 21-25
        variable: '%level%'

  apply_LevellingVariance:
#   This Strategy Preset controls the random level variance applied.
    name: 'LVLling Strategy - Apply Variance'
    strategies:
      max-random-variance: 2

  ycoord_Levelling:
#   This Strategy Preset controls Y-Coordinate-Levelling.
    name: 'LVLling Strategy - Y-LVLling'
    strategies:
      y-coordinate:
        start: 100
        end: 20
        period: 0

  allowed_worlds:
#   This controls the allowed worlds to apply levels too.
    name: 'Excluded Worldlist'
    conditions:
      worlds:
#        allowed-list: ['*']
        excluded-list: ['']

  hard_difficulty:
#   This establishes the minimum and maximum levels, and the multipliers, for HARD.
    name: 'HARD Difficulty Multipliers'
    apply-settings:
      minLevel: 1
      maxLevel: 50
      multipliers:
        max-health: 8.0
        movement-speed: 0.25
        attack-damage: 3.5
        ranged-attack-damage: 2.75
        creeper-blast-damage: 1.25
        follow-range: 0.25
        item-drop: 3
        xp-drop: 5
#       Special Multipliers (0.0 Min - 1.0 Max)
        armor-bonus: 0.3
        armor-toughness: 0.3
        attack-knockback: 0.5
        knockback-resistance: 0.5
        zombie-spawn-reinforcements: 0.45

      creeper-max-damage-radius: 5
      tiered-coloring:
        1-9: '&#22E76B' #Green
        10-19: '&#528CFF' #Blue
        20-29: '&#FFCD56' #Yellow
        30-39: '&#F2003D' #Red
        40-50: '&#B447FF' #Purple
        default: '&#FFFFFF' #White
      health-indicator:
        scale: 8
        max: 5
        merge: true

  normal_difficulty:
#   This establishes the minimum and maximum levels, and the multipliers, for NORMAL.
    name: 'NORMAL Difficulty Multipliers'
    apply-settings:
      minLevel: 1
      maxLevel: 25
      multipliers:
#       All Entities/Default Attributes
        max-health: 5.0
        movement-speed: 0.15
        attack-damage: 2.25
        ranged-attack-damage: 2.0
        creeper-blast-damage: 1.0
        follow-range: 0
        item-drop: 3
        xp-drop: 5
#       Special Multipliers (0.0 Min - 1.0 Max)
        armor-bonus: 0.2
        armor-toughness: 0.15
        attack-knockback: 0.25
        knockback-resistance: 0.2
        zombie-spawn-reinforcements: 0.25

      creeper-max-damage-radius: 3
      tiered-coloring:
        1-5: '&#22E76B' #Green
        6-10: '&#528CFF' #Blue
        11-15: '&#FFCD56' #Yellow
        16-20: '&#F2003D' #Red
        21-25: '&#B447FF' #Purple
        default: '&#FFFFFF' #White
      health-indicator:
        scale: 4
        max: 5
        merge: true

  easy_difficulty:
#   This establishes the minimum and maximum levels, and the multipliers, for EASY.
    name: 'EASY Difficulty Multipliers'
    apply-settings:
      minLevel: 1
      maxLevel: 10
      multipliers:
        max-health: 2.5
        movement-speed: 0.05
        attack-damage: 1.0
        ranged-attack-damage: 1.0
        creeper-blast-damage: 0.5
        follow-range: 0
        item-drop: 3
        xp-drop: 5
#       Special Multipliers (0.0 Min - 1.0 Max)
        armor-bonus: 0.1
        armor-toughness: 0.0
        attack-knockback: 0.1
        knockback-resistance: 0.15
        zombie-spawn-reinforcements: 0.1

      creeper-max-damage-radius: 1
      tiered-coloring:
        1-2: '&#22E76B' #Green
        3-4: '&#528CFF' #Blue
        5-6: '&#FFCD56' #Yellow
        7-8: '&#F2003D' #Red
        9-10: '&#B447FF' #Purple
        default: '&#FFFFFF' #White
      health-indicator:
        scale: 2
        max: 5
        merge: true

  nametag_using_indicator:
#   This controls the nametag, where the health is displayed using %health-indicator%
    name: 'Nametag - Health Indicator'
    apply-settings:
      nametag: '&8&l༺ %tiered%Lvl %mob-lvl%&8 | &f%displayname%&8 | &f%entity-health-rounded% %tiered%%heart_symbol% &r%health-indicator% &8&l༻'
      health-indicator:
        indicator: '█'
        indicator-half: '▌'
        colored-tiers:
          tier-1: '&#22E76B' #Green
          tier-2: '&#528CFF' #Blue
          tier-3: '&#FFCD56' #Yellow
          tier-4: '&#FE803C' #Orange
          tier-5: '&#F2003D' #Red
          tier-6: '&#B447FF' #Purple
          default: '&#FFFFFF' #White
        merge: true

  nametag_using_numbers:
#   This controls the nametag, where the health is displayed using %entity-health-rounded%
    name: 'Nametag - Health Numerical'
    apply-settings:
      nametag: '&8&l༺ &a%tiered%Lvl %mob-lvl%&8 | &f%displayname%&8 | &f%entity-health-rounded%&8/&f%entity-max-health-rounded% %tiered%%heart_symbol% &8&l༻'

default-rule:
  use-preset:
    - allowed_worlds
#    - nametag_using_numbers
    - nametag_using_indicator
#    - hard_difficulty
#    - normal_difficulty
#    - easy_difficulty
#    - apply_LevellingVariance
#    - weighted_random_hard
#    - weighted_random_normal
#    - weighted_random_easy
#    - spawn_Levelling
#    - blended_Levelling
#    - ycoord_Levelling
#    - random_Levelling
#    - player_Levelling

  conditions:
    allowed-spawn-reasons:
      excluded-list: [SPAWNER_EGG]

    level-plugins:
      DANGEROUS_CAVES: false
      ECO_BOSSES: false
      MYTHIC_MOBS: true
      ELITE_MOBS: false
      ELITE_MOBS_NPCS: false
      ELITE_MOBS_SUPER_MOBS: false
      INFERNAL_MOBS: false
      CITIZENS: false
      SHOPKEEPERS: false
      SIMPLE_PETS: false
      ELITE_BOSSES: false
      BLOOD_NIGHT: false

#    apply-above-y: 64
#    apply-below-y: 59
#    min-distance-from-spawn: 1000
#    max-distance-from-spawn: 5000

    mob-customname-status: EITHER
    mob-tamed-status: EITHER

  apply-settings:
    sunlight-intensity: 5

    entity-name-override:
      HUSK: ['Husk', 'Desert Zombie', 'Lost Soul', 'Dessicated Corpse']
      SKELETON: ['Bones', 'Billy Bones', 'Verta Brae', 'Skeleton']
      PILLAGER: ['Raider', 'Barbarian', 'Pillager']
      ZOMBIE: ['Walkers', 'Zombie', 'Geek', 'Lurker', 'Biter', 'Infected', 'Infected Human', 'Infected Warrior', 'Runner']
      CREEPER: ['Fizzle', 'Blast', 'Destroyer', 'Bombast', 'Badaboom', 'Bomber', 'Demolition', 'Slither', 'Creep', 'Creeper']
      ENDERMAN: ['Slender', 'Slendy', 'Enderman', 'Teleb', 'Endie', 'Skulk', 'Lurch', 'Blinks', 'Umbra']
      SPIDER: ['Spider', 'Theridiidae', 'Agelenidae', 'Oxyopidae', 'Sydney', 'Arthropod', 'Webster', 'Ocho', 'Furball', 'Spike', 'Silky', 'Fang']

    creature-death-nametag: '%tiered%Lvl %mob-lvl%&8 | &f%entity-name%'
    nametag-visible-time: 60
    nametag-visibility-method: ['MELEE', 'ATTACKED']

    baby-mobs-inherit-adult-setting: true
    level-inheritance: true
    passenger-match-level: false

    use-custom-item-drops-for-mobs: true


# +-------------------------------------------------------------------------------------------LM3
# +                                                                                          +LM3
# +   H I G H E S T   P R I O R I T Y                                                        +LM3
# +   Section 04 - Custom Rules                                                              +LM3
# +                                                                                          +LM3
# +   This section applies CUSTOM RULES, or exceptions, to the DEFAULT RULE. These rules     +LM3
# +   modify the DEFAULT RULE to achieve your desired effect. Establish a CONDITION to       +LM3
# +   check for, then set either a STRATEGY or APPLY-SETTINGS when the CONDITION is met.     +LM3
# +   If you need help understanding CUSTOM RULES, read the official LevelledMobs Wiki!      +LM3
# +   https://github.com/lokka30/LevelledMobs/wiki/Documentation---rules.yml#custom-rules    +LM3
# +                                                                                          +LM3
# +-------------------------------------------------------------------------------------------LM3
custom-rules:
  - enabled: true
    priority: 1
    name: 'CR - NoLevel All Passive + EntityTypes'
    use-preset: allowed_worlds
    conditions:
      entities:
        allowed-groups: ['all_passive_mobs']
        allowed-list: ['BABY_', 'WITHER', 'VILLAGER', 'WANDERING_TRADER', 'BAT', 'ENDER_DRAGON']
    apply-settings:
      maxLevel: 0

  - enabled: true
    name: 'CR - Custom World Levelling'
    conditions:
      worlds:
        allowed-list: ['world']
    strategies:
      player-levelling:
        match-level: false
        use-player-max-level: false
        player-level-scale: 1.0
        decrease-level: true
        level-cap: 26
        tiers:
          1-25: 1-5
          26-35: 6-10
          36-45: 11-15
          46-65: 16-20
          66-100: 21-25
        variable: '%ecoskills_total_skill_level%'
    apply-settings:
      baby-mobs-inherit-adult-setting: true
      creeper-max-damage-radius: 6
      level-inheritance: true
      maxLevel: 25
      multipliers:
        max-health: 3.4
        attack-damage: 1.4
        ranged-attack-damage: 1.35
        item-drop: 0.2
        xp-drop: 0.5
        armor-bonus: 0.003
        armor-toughness: 0.008
        attack-knockback: 0.003
        knockback-resistance: 0.005
        zombie-spawn-reinforcements: 0.0
        follow-range: 0.003
      tiered-coloring:
        1-25: '&#ffffff'
        26-35: '&#08fa00'
        36-45: '&#fff700'
        46-65: '&#ff0000'
        66-100: '&#ea00ff'

  - enabled: true
    name: 'CR - Custom Nether/End Levelling'
    conditions:
      worlds:
        allowed-list: ['world_nether', 'world_the_end']
    strategies:
      player-levelling:
        match-level: false
        use-player-max-level: false
        player-level-scale: 1.0
        decrease-level: true
        level-cap: 26
        tiers:
          1-25: 1-5
          26-35: 6-10
          36-45: 11-15
          46-65: 16-20
          66-100: 21-25
        variable: '%ecoskills_total_skill_level%'
    apply-settings:
      baby-mobs-inherit-adult-setting: true
      creeper-max-damage-radius: 6
      level-inheritance: true
      maxLevel: 25
      multipliers:
        max-health: 4.0
        attack-damage: 1.4
        ranged-attack-damage: 1.35
        item-drop: 0.2
        xp-drop: 0.5
        armor-bonus: 0.003
        armor-toughness: 0.008
        attack-knockback: 0.003
        knockback-resistance: 0.005
        zombie-spawn-reinforcements: 0.0
        follow-range: 0.003
        custom-mob-level:
          SHULKER:
            max-health: 10.0
            ranged-attack-damage: 0.5
        custom-mob-level:
          ENDERMAN:
            max-health: 4.0
            attack-damage: 0.7
      tiered-coloring:
        1-25: '&#ffffff'
        26-35: '&#08fa00'
        36-45: '&#fff700'
        46-65: '&#ff0000'
        66-100: '&#ea00ff'

  - enabled: false
    name: 'CR - Custom Nether Levelling'
    use-preset: normal_difficulty, apply_LevellingVariance
    conditions:
      worlds:
        allowed-list: ['world_nether']
    strategies:
      y-coordinate:
        start: 100
        end: 40
        period: 0

  - enabled: false
    name: 'CR - Custom Entity Attributes'
    use-preset: allowed_worlds
    apply-settings:
      multipliers:
        custom-mob-level:
          ENDERMAN:
            max-health: 0.0
            movement-speed: 0.0
          SILVERFISH:
            max-health: 0.0
            movement-speed: 0.0
          CREEPER:
            movement-speed: 0.025
          WITHER_SKELETON:
            max-health: 1.0

  - enabled: true
    name: 'CR - Custom Ender Dragon Levelling'
    conditions:
      worlds:
        allowed-list: ['world_the_end']
      entities:
        allowed-list: ['ENDER_DRAGON']
    strategies:
      player-levelling:
        match-level: false
        use-player-max-level: false
        player-level-scale: 1.0
        decrease-level: true
        level-cap: 26
        tiers:
          31-50: 21-25
        variable: '%ecoskills_total_skill_level%'
    apply-settings:
      maxLevel: 25
      multipliers:
        custom-mob-level:
          ENDER_DRAGON:
            max-health: 50.0
            attack-damage: 25.0
            ranged-attack-damage: 25.0
            xp-drop: 25.0
            attack-knockback: 0.5
      tiered-coloring:
        100-100: '&#ff0000'








  - enabled: false
    name: 'all hostile mobs'
    conditions:
      worlds: ['world', 'world_nether']
      entities:
        allowed-groups: ['all_hostile_mobs']
    apply-settings:
      use-droptable-id: 'hostile_mobs'

  - enabled: true
    name: 'end mobs'
    conditions:
      worlds: 'world_the_end'
    apply-settings:
      use-droptable-id: 'executableitems_boss_warp_the_end'

# +-------------------------------------------------------------------------------------------LM3
# +                                                                                          +LM3
# +   Section 05 - Advanced Message Settings                                                 +LM3
# +   DO NOT EDIT BEYOND HERE WITHOUT DEVELOPER APPROVAL                                     +LM3
# +                                                                                          +LM3
# +-------------------------------------------------------------------------------------------LM3
file-version: 2
```

</details>
