### ISSUE TITLE
Spawn a mob on one level 

### ISSUE THREAD

**Issue by FortiethSwing61** [lokka30/LevelledMobs#394]
Can you now spawn a mob only one level?
I want the Ender Dragon to always spawn on Level 100

**Comment by stumper66** [comment]
@FortiethSwing61 
add this custom rule
```
  - enabled: true
    name: 'EnderDragon'
    conditions:
      entities: 'ENDER_DRAGON'
    apply-settings:
      minLevel: 100
      maxLevel: 100
```
