### ISSUE TITLE
Add 'primary label' system to LM4 API

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#415]
On the [ArcanePlugins Discord Server](https://www.discord.io/arcaneplugins), there is a [discussion](https://discord.com/channels/752310043214479462/757933745620779033/1024146891996418128) on how this will be implemented.

This will provide compatibility for ItemsAdder (https://github.com/PluginBugs/Issues-ItemsAdder/issues/1116) and also some plugins by AlonsoAliaga, among others we are unaware of.

```yaml
- action: 'set-packet-label'
  formula: 'Lvl.%entity-level% %entity-name%'
  primary: true
- action: 'set-boss-bar-label'
  formula: 'Lvl.%entity-level% %entity-name%'
 #primary: false
```
